import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(18,GPIO.OUT)
GPIO.setup(17,GPIO.OUT)
GPIO.setup(16,GPIO.OUT)
print("Green on")
GPIO.output(18,GPIO.HIGH)
time.sleep(5)
print("Green off")
GPIO.output(18,GPIO.LOW)
print("Yellow on")
GPIO.output(17,GPIO.HIGH)
time.sleep(1)
print("Yellow off")
GPIO.output(17,GPIO.LOW)
print("Red on")
GPIO.output(16,GPIO.HIGH)
time.sleep(4)
print("Red off")
GPIO.output(16,GPIO.LOW)
